# tasks file for ntp
---
- name: install
  apt:
    name: ntp
    state: latest
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - ntp
    - ntp-install

- name: update configuration file
  template:
    src: etc/ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
  notify: restart ntp
  tags:
    - configuration
    - ntp
    - ntp-configuration
