---
# tasks file for ntp
- name: install
  apt:
    name: ntp
    state: latest
  tags: [configuration, ntp, ntp-install]

- name: update configuration file
  template:
    src: etc/ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
  notify: restart ntpd
  tags: [configuration, ntp, ntp-configuration]
